# Generated by Django 5.0.6 on 2024-08-06 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_projects'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
