# Generated by Django 5.0.6 on 2024-08-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_clientopinion'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientopinion',
            name='occupation',
            field=models.CharField(default='Student', max_length=20),
            preserve_default=False,
        ),
    ]
