# Generated by Django 5.0.6 on 2024-08-11 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_clientopinion_occupation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientopinion',
            old_name='client',
            new_name='name',
        ),
    ]
