# Generated by Django 5.0.6 on 2024-10-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(blank=True, choices=[('DEVELOPMENT', 'Development'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
    ]
