# Generated by Django 5.0.6 on 2024-10-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publication_date',
            field=models.DateField(default='2024-01-01', verbose_name='Date when the article was published.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='read_length',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('DEVELOPMENT', 'Development'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
