# Generated by Django 5.0.6 on 2024-10-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_project_image_project_fa_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='fa_class',
        ),
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project_images'),
        ),
        migrations.AddField(
            model_name='service',
            name='fa_class',
            field=models.TextField(blank=True, null=True),
        ),
    ]
