# Generated by Django 5.0.6 on 2024-10-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_project_fa_class_remove_service_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='fa_class',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
