# Generated by Django 5.0.6 on 2024-10-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_service_fa_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='fa_class',
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='service_images'),
        ),
    ]
