# Generated by Django 5.0.6 on 2024-10-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_service_fa_class_service_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('source', models.CharField(choices=[('udemy', 'Udemy'), ('other', 'Other (Specify)')], default='other', max_length=50)),
                ('source_custom', models.CharField(blank=True, help_text='Specify if Other', max_length=30, null=True)),
                ('date_issued', models.DateField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='certification_icons/')),
                ('url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_issued'],
            },
        ),
    ]
