# Generated by Django 5.0.6 on 2024-10-28 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_certification'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Certification',
            new_name='Certificate',
        ),
    ]
