# Generated by Django 5.0.6 on 2024-10-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_rename_certification_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='certification_icons/'),
        ),
    ]
