# Generated by Django 5.0.6 on 2024-10-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_certificate_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='date_issued',
            field=models.DateField(blank=True, null=True),
        ),
    ]
