# Generated by Django 5.0.6 on 2024-10-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_certificate_date_issued'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
    ]
