# Generated by Django 5.0.6 on 2024-10-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_article_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='overview',
        ),
        migrations.AddField(
            model_name='project',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
    ]
