# Generated by Django 5.0.6 on 2024-10-28 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_rename_description_project_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='content',
            new_name='description',
        ),
    ]
