# Generated by Django 5.0.6 on 2024-10-28 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_project_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='source',
            field=models.CharField(choices=[('Udemy', 'Udemy'), ('Other', 'Other (Specify)')], default='other', max_length=50),
        ),
    ]
