# Generated by Django 5.0.6 on 2024-10-28 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_certificate_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.CharField(blank=True, choices=[('Development', 'Development'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Development', 'Development'), ('Other', 'Other')], max_length=20),
        ),
    ]
