# Generated by Django 5.0.6 on 2024-10-28 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_article_tags_alter_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated list of tags', max_length=100, null=True),
        ),
    ]
