# Generated by Django 5.0.6 on 2024-11-23 16:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='article_images', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='certification_icons/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg', 'svg'])]),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='source',
            field=models.CharField(choices=[('Udemy', 'Udemy'), ('Other', 'Other (Specify)')], default='Other', max_length=50),
        ),
        migrations.AlterField(
            model_name='clientopinion',
            name='stars',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='expertarea',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='expert_area_icons', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project_images', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/additional_images', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='service_images', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg', 'svg'])]),
        ),
    ]
