# Generated by Django 5.0.6 on 2024-11-23 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_alter_project_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='years_of_experience',
        ),
    ]
