# Generated by Django 5.0.6 on 2024-11-23 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_remove_profile_years_of_experience'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-publication_date'], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['-date_issued'], 'verbose_name': 'Certificate', 'verbose_name_plural': 'Certificates'},
        ),
        migrations.AlterModelOptions(
            name='clientopinion',
            options={'verbose_name': 'Client Opinion', 'verbose_name_plural': 'Client Opinions'},
        ),
        migrations.AlterModelOptions(
            name='expertarea',
            options={'verbose_name': 'Expert Area', 'verbose_name_plural': 'Expert Areas'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-id'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='workexperience',
            options={'verbose_name': 'Work Experience', 'verbose_name_plural': 'Work Experiences'},
        ),
    ]
