# Generated by Django 5.0.6 on 2024-11-23 16:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_alter_article_options_alter_certificate_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientopinion',
            name='stars',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
