# Generated by Django 5.1.5 on 2025-03-11 01:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_article_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="media/article_images",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "png", "jpeg"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="icon",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="media/certification_icons",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "png", "jpeg", "svg"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="expertarea",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="media/expert_area_icons",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "png", "jpeg"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="media/project_images",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "png", "jpeg"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="image",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="media/service_images",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "png", "jpeg", "svg"]
                    )
                ],
            ),
        ),
    ]
