# Generated by Django 5.1.5 on 2025-03-31 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="source",
            field=models.CharField(
                choices=[
                    ("Udemy", "Udemy"),
                    ("LinkedIn", "LinkedIn"),
                    ("Other", "Other (Specify)"),
                ],
                default="Other",
                max_length=50,
            ),
        ),
    ]
