# Generated by Django 5.1.5 on 2025-04-05 18:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_alter_certificate_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="resume",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="media/pdfs",
                validators=[django.core.validators.FileExtensionValidator(["pdf"])],
            ),
        ),
    ]
