# Generated by Django 5.2.7 on 2025-10-18 09:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_alter_projectimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="article_images",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "png", "jpeg"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="icon",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="certification_icons",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "png", "jpeg", "svg"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="expertarea",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="expert_area_icons",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "png", "jpeg"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profile_images",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "png", "jpeg"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="resume",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="pdfs",
                validators=[django.core.validators.FileExtensionValidator(["pdf"])],
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="project_images",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "png", "jpeg"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="projectimage",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="project_images/additional_images",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "png", "jpeg"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="image",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="service_images",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "png", "jpeg", "svg"]
                    )
                ],
            ),
        ),
    ]
